openapi: 3.0.0
info:
  description: API for managing authors in an online bookstore.
  title: Bookstore API - Authors
  version: 1.0.0
servers:
- url: /
paths:
  /authors:
    get:
      parameters:
      - description: The page number to retrieve. Defaults to 1 if not specified.
        explode: true
        in: query
        name: pageNumber
        required: false
        schema:
          default: 1
          type: integer
        style: form
      - description: The number of items per page. Defaults to 25 if not specified.
        explode: true
        in: query
        name: pageSize
        required: false
        schema:
          default: 25
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_authors_get_200_response'
          description: A JSON array of authors
      summary: Get a list of authors
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
        required: true
      responses:
        "201":
          description: Author created successfully
      summary: Add a new author
  /authors/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Author deleted successfully
        "404":
          description: Author not found
      summary: Delete an author by ID
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Author'
          description: A single author
        "404":
          description: Author not found
      summary: Get a specific author by ID
    patch:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
        required: true
      responses:
        "200":
          description: Author updated successfully
        "404":
          description: Author not found
      summary: Update an author by ID
components:
  schemas:
    Author:
      example:
        address:
          zipcode: zipcode
          country: country
          unit: unit
          city: city
          state: state
          landmark: landmark
          street_name: street_name
        languages:
        - languages
        - languages
        dob: 2000-01-23
        name:
          last_name: last_name
          middle_name: middle_name
          first_name: first_name
        id: id
      properties:
        id:
          type: string
        name:
          $ref: '#/components/schemas/Author_name'
        dob:
          format: date
          type: string
        address:
          $ref: '#/components/schemas/Author_address'
        languages:
          items:
            type: string
          type: array
      required:
      - address
      - dob
      - id
      - languages
      - name
      type: object
    _authors_get_200_response:
      example:
        totalItems: 0
        totalPages: 6
        pageSize: 5
        currentPage: 1
        authors:
        - address:
            zipcode: zipcode
            country: country
            unit: unit
            city: city
            state: state
            landmark: landmark
            street_name: street_name
          languages:
          - languages
          - languages
          dob: 2000-01-23
          name:
            last_name: last_name
            middle_name: middle_name
            first_name: first_name
          id: id
        - address:
            zipcode: zipcode
            country: country
            unit: unit
            city: city
            state: state
            landmark: landmark
            street_name: street_name
          languages:
          - languages
          - languages
          dob: 2000-01-23
          name:
            last_name: last_name
            middle_name: middle_name
            first_name: first_name
          id: id
      properties:
        totalItems:
          description: Total number of authors available.
          type: integer
        totalPages:
          description: Total number of pages.
          type: integer
        currentPage:
          description: The current page number.
          type: integer
        pageSize:
          description: The number of items per page.
          type: integer
        authors:
          items:
            $ref: '#/components/schemas/Author'
          type: array
      type: object
    Author_name:
      example:
        last_name: last_name
        middle_name: middle_name
        first_name: first_name
      properties:
        first_name:
          type: string
        middle_name:
          type: string
        last_name:
          type: string
      type: object
    Author_address:
      example:
        zipcode: zipcode
        country: country
        unit: unit
        city: city
        state: state
        landmark: landmark
        street_name: street_name
      properties:
        unit:
          type: string
        street_name:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        zipcode:
          type: string
        landmark:
          type: string
      type: object
